const translations = [
  {
    de: {
      TITLE: 'Originaltitel',
      RUNTIME: 'Länge',
      DATE: 'Erscheinungsdatum',
      SCORE: 'Bewertung',
      VOTES: 'Stimmen',
      STORY: 'Die Handlung',
      SITE: 'Webseite',
      NOSTORY: 'Leider gibt es keine Beschreibung für diesen Film  :-(',
      CHOOSE_LANG: 'Spracheinstellung:',
      APPLY: 'Sprache verwenden',
      SEARCH_TITLE: 'Film Finden',
      SEARCH_PROMPT: 'Film suchen...',
      SEARCH_MESSAGE: 'Bitte Text eingeben um die Suche zu starten...',
      SETTINGS: 'Einstellungen',
      YEAR: 'Jahr',
      ON_LIST: 'auf der Liste',
      REGIE: 'Regie',
      CREW_TITLE: 'Filmcrew',
      CAST_TITLE: 'Besetzung',
      CREDITS: 'Mitwirkende',
      ROLE: 'In der Rolle von ',
      JOB: 'Position',
      AS: 'Rolle:',
      NO_INFO: 'Keine Information verfügbar',
      BORN: 'Geboren am',
      DIED: 'Verstorben am',
      IN: 'in',
      BIOGRAPHY: 'Biographie',
      NO_PHOTO: 'Kein Foto verfügbar',
      PROFILE: 'Steckbrief von',
      SHOW_MOVIES: 'Filme mit',
      MOVIES: 'Filme'
    },
    en: {
      TITLE: 'Original Title',
      RUNTIME: 'Runtime',
      DATE: 'Release Date',
      SCORE: 'Rating',
      VOTES: 'votes',
      STORY: 'The Story',
      SITE: 'Website',
      NOSTORY: 'Sorry, there is no description available :-(',
      CHOOSE_LANG: 'Language Settings:',
      APPLY: 'Use this Language',
      SEARCH_TITLE: 'Find Movie',
      SEARCH_PROMPT: 'Search for movies...',
      SEARCH_MESSAGE: 'Type some text to search for movies...',
      SETTINGS: 'Settings',
      YEAR: 'Year',
      ON_LIST: 'on this list',
      REGIE: 'Director',
      CREW_TITLE: 'Film Crew',
      CAST_TITLE: 'Cast',
      CREDITS: 'Credits',
      ROLE: 'In the role of',
      AS: 'Role:',
      JOB: 'Job',
      NO_INFO: 'No information available',
      BORN: 'Born on',
      DIED: 'Died on',
      IN: 'in',
      BIOGRAPHY: 'Biography',
      NO_PHOTO: 'No photo available',
      PROFILE: 'Profile of',
      SHOW_MOVIES: 'Movies with',
      MOVIES: 'Movies'
    },
    fr: {
      TITLE: 'Titre Original',
      RUNTIME: 'Durée',
      DATE: 'Date de Publication',
      SCORE: 'Évaluations',
      VOTES: 'votes',
      STORY: 'Description',
      SITE: 'Page Web',
      NOSTORY: "Désolé, il n'y a pas de description pour ce film :-(",
      CHOOSE_LANG: 'Paramètres de Langue:',
      APPLY: 'Utiliser cette Langue',
      SEARCH_TITLE: 'Trouver un Film',
      SEARCH_PROMPT: 'Chercher des films...',
      SEARCH_MESSAGE: 'Saisir un texte pour lancer la recherche...',
      SETTINGS: 'Paramètres',
      YEAR: 'Année',
      ON_LIST: 'sur ce liste',
      REGIE: 'Réalisation',
      CREW_TITLE: 'Équipe',
      CAST_TITLE: 'Acteurs ',
      CREDITS: 'Générique',
      ROLE: 'Dans le rôle de ',
      AS: 'Rôle :',
      JOB: 'Job',
      NO_INFO: "Pas d'information disponible",
      BORN: 'Né le',
      DIED: 'Décédé le',
      IN: 'à',
      BIOGRAPHY: 'Biographie',
      NO_PHOTO: "Pas d'photo disponible",
      PROFILE: 'Portrait de',
      SHOW_MOVIES: 'Films avec',
      MOVIES: 'Films'
    }
  }
];

export default translations;
